name: Deploy Ology Brewing Plugin

on:
  push:
    branches: [main, develop, feature/*, hotfix/*]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy-to-development:
    runs-on: ubuntu-latest
    environment: development
    # Deploy to development for all pushes except main
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP (Development)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*"
          target: "/home/ologybrewing/website-dev/wp-content/plugins/ology-brewing"

      - name: Set Permissions (Development)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}

  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    # Only deploy to production when PRs are merged into main
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP (Production)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*"
          target: "/home/ologybrewing/website/wp-content/plugins/ology-brewing"

      - name: Set Permissions (Production)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
