name: Deploy OnTap Plugin

on:
  push:
    branches: [main, develop, feature/*, hotfix/*, claude/*]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy-to-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP (Production)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*"
          target: "/home/onscripttech-ontap/htdocs/ontap.onscripttech.com/wp-content/plugins/ontap"
